"""create todos relationship

Revision ID: 2d0d7a7a70bb
Revises: f32c2ba4e039
Create Date: 2024-09-28 07:38:43.351262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0d7a7a70bb'
down_revision: Union[str, None] = 'f32c2ba4e039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
